# 홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정 
# 실전투자(개발계)
APP_KEY: "P***N"
APP_SECRET: "/3G***QQ="

# 계좌번호 앞 8자리 / 뒤 2자리
# 실전투자
CANO: "계좌번호 앞 8자리" 
ACNT_PRDT_CD: "계좌번호 뒤 2자리"

#실전투자
URL_BASE: "http://210.107.75.78:9443"

# HTS ID
# 실전투자
HTS_ID: "accnt002"
