# 홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정 
# 실전투자
# APP_KEY: "P...d8"
# APP_SECRET: "uZ...lQ="
# 모의투자
APP_KEY: "P...7r1"
APP_SECRET: "G...hM="

# 계좌번호 앞 8자리 / 뒤 2자리
# 실전투자
# CANO: "12345678" 
# ACNT_PRDT_CD: "01"
# 모의투자
CANO: "12345678" 
ACNT_PRDT_CD: "01"

#실전투자
# URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

# HTS ID
# 실전투자
# HTS_ID: "aaaa1234"
#모의투자
HTS_ID: "aaaa1234"