# 홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정 
# 실전투자
APP_KEY: "PShp12vxqLPCVLNejlfydRUo4e0hSv5ynDh1"
APP_SECRET: "vXpB908NxwdWUpxhilq7l/6LFfGnNOvnGneuVAjg6oiTBciCzZ2Ts5HwXIBuenAZTYI+5yAMUjDHG7ZqOjB/bj+A9ZVjF70MDvdVcnC+ddzEvh0ZAYRs0H5QPEOle9KA2SmqnGKrcqYKgVp4fjCVpQWjhR9MQ1ZDysqAi30PoF6d3tAKkZI="
# 모의투자
# APP_KEY: "P...7r1"
# APP_SECRET: "G...hM="

# 계좌번호 앞 8자리 / 뒤 2자리
# 실전투자
CANO: "63614617" 
ACNT_PRDT_CD: "01"
# 모의투자
# CANO: "12345678" 
# ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

# HTS ID
# 실전투자
HTS_ID: "@1678001"
#모의투자
# HTS_ID: "aaaa1234"